### PR TITLE
[UPGRADE] Handle dart3

### PR DESCRIPTION
**Pull request by TiluWeb**
I have modified the limitations of the sdk version and the http package to accept dart 3.

### CODE REVIEW

**Comment by TiluWeb** [comment]
@ahmedsaleh210 I can't add you as reviews, It that deliberate ?

**Comment by ahmedsaleh210** [comment]
Thanks for the GitHub pull request! I've accepted your update to package. Your help is much appreciated.

**Comment by TiluWeb** [comment]
Glad to help you.
Do you know how soon will these modifications be deployed on pub dev ?

**Comment by TiluWeb** [comment]
@ahmedsaleh210 Do you know how soon will these modifications be deployed on pub dev ?

**Comment by TiluWeb** [comment]
@ahmedsaleh210 can you please deploy this new version on pub dev ?

**Pull request merged**
